// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/export": {
            "get": {
                "description": "Downloads the full transaction history as an Excel workbook.",
                "produces": [
                    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                ],
                "tags": [
                    "export"
                ],
                "summary": "Export transactions to Excel (.xlsx)",
                "responses": {
                    "200": {
                        "description": "Excel file download",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "500": {
                        "description": "Error while building the Excel workbook",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/summary": {
            "get": {
                "description": "Returns the overall total, the current month's total and the number of recorded transactions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "metrics"
                ],
                "summary": "Get summary metrics",
                "responses": {
                    "200": {
                        "description": "Example: {'total_general': 5000.5, 'total_mes': 1200.0, 'conteo': 14}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Server error while computing the summary",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/transactions": {
            "get": {
                "description": "List (GET), create (POST), update (PUT) and delete (DELETE) financial transactions, using multipart/form-data or JSON.",
                "consumes": [
                    "application/json",
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Manage transactions (CRUD)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Transaction ID (required only for DELETE)",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Transaction ID (required only for PUT with form data)",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Payment date (DD/MM/YYYY)",
                        "name": "fecha_pago",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Description of the expense",
                        "name": "descripcion",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Transaction amount",
                        "name": "monto",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "City of the transaction",
                        "name": "ciudad",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Bank used",
                        "name": "banco_usado",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Bank reference number",
                        "name": "referencia",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Existing image path, kept if no new file is uploaded",
                        "name": "imagen_path",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Receipt image file",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success (GET returns the list, PUT confirms the update)",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Transaccion"
                            }
                        }
                    },
                    "201": {
                        "description": "Transaction created (POST)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "List (GET), create (POST), update (PUT) and delete (DELETE) financial transactions, using multipart/form-data or JSON.",
                "consumes": [
                    "application/json",
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Manage transactions (CRUD)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Transaction ID (required only for DELETE)",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Transaction ID (required only for PUT with form data)",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Payment date (DD/MM/YYYY)",
                        "name": "fecha_pago",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Description of the expense",
                        "name": "descripcion",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Transaction amount",
                        "name": "monto",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "City of the transaction",
                        "name": "ciudad",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Bank used",
                        "name": "banco_usado",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Bank reference number",
                        "name": "referencia",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Existing image path, kept if no new file is uploaded",
                        "name": "imagen_path",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Receipt image file",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success (GET returns the list, PUT confirms the update)",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Transaccion"
                            }
                        }
                    },
                    "201": {
                        "description": "Transaction created (POST)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "List (GET), create (POST), update (PUT) and delete (DELETE) financial transactions, using multipart/form-data or JSON.",
                "consumes": [
                    "application/json",
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Manage transactions (CRUD)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Transaction ID (required only for DELETE)",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Transaction ID (required only for PUT with form data)",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Payment date (DD/MM/YYYY)",
                        "name": "fecha_pago",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Description of the expense",
                        "name": "descripcion",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Transaction amount",
                        "name": "monto",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "City of the transaction",
                        "name": "ciudad",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Bank used",
                        "name": "banco_usado",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Bank reference number",
                        "name": "referencia",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Existing image path, kept if no new file is uploaded",
                        "name": "imagen_path",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Receipt image file",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success (GET returns the list, PUT confirms the update)",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Transaccion"
                            }
                        }
                    },
                    "201": {
                        "description": "Transaction created (POST)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "List (GET), create (POST), update (PUT) and delete (DELETE) financial transactions, using multipart/form-data or JSON.",
                "consumes": [
                    "application/json",
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "transactions"
                ],
                "summary": "Manage transactions (CRUD)",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Transaction ID (required only for DELETE)",
                        "name": "id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Transaction ID (required only for PUT with form data)",
                        "name": "id",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Payment date (DD/MM/YYYY)",
                        "name": "fecha_pago",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Description of the expense",
                        "name": "descripcion",
                        "in": "formData"
                    },
                    {
                        "type": "number",
                        "description": "Transaction amount",
                        "name": "monto",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "City of the transaction",
                        "name": "ciudad",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Bank used",
                        "name": "banco_usado",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Bank reference number",
                        "name": "referencia",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "Existing image path, kept if no new file is uploaded",
                        "name": "imagen_path",
                        "in": "formData"
                    },
                    {
                        "type": "file",
                        "description": "Receipt image file",
                        "name": "image",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success (GET returns the list, PUT confirms the update)",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Transaccion"
                            }
                        }
                    },
                    "201": {
                        "description": "Transaction created (POST)",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal database error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/whatsapp/logout": {
            "post": {
                "description": "Unlinks the device and asynchronously starts a fresh pairing flow that serves a new QR code.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "whatsapp"
                ],
                "summary": "Log out of WhatsApp and regenerate the QR code",
                "responses": {
                    "200": {
                        "description": "Credentials reset confirmation: {'status': 'resetting'}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/whatsapp/send": {
            "post": {
                "description": "Asynchronously queues a structured report to a WhatsApp group or contact, preventing concurrent duplicate sends.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "whatsapp"
                ],
                "summary": "Send a transaction to WhatsApp",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID of the transaction to send",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Recipient group name or JID (default: 'Prueba')",
                        "name": "to",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Queue state of the send: 'queued' or 'processing'",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Transaction or target group not found",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "503": {
                        "description": "WhatsApp client is not initialized or connected",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/whatsapp/status": {
            "get": {
                "description": "Returns the current connection state, any persistent error, the active pairing QR code, or the list of joined groups.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "whatsapp"
                ],
                "summary": "WhatsApp connection status",
                "responses": {
                    "200": {
                        "description": "Client state and joined groups",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Transaccion": {
            "type": "object",
            "properties": {
                "banco_usado": {
                    "type": "string"
                },
                "ciudad": {
                    "type": "string"
                },
                "descripcion": {
                    "type": "string"
                },
                "fecha_pago": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "imagen_path": {
                    "type": "string"
                },
                "monto": {
                    "type": "number"
                },
                "referencia": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "api.example.com",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Verification of Expenses - Transactions & Reports API",
	Description:      "Go backend for expense tracking, receipt storage, Excel reporting and WhatsApp notifications.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
